Error on: C:\L2j-Gracia-Final\GAMESERVER\data\scripts\ai\individual\vanhalter.py.error.log
Line: -1 - Column: -1

Traceback (innermost last):
  File "vanhalter.py", line 6, in ?
ImportError: no module named grandbosses
